<?php
Define('W_NUMBER','2040');
Define('W_COMPANY','搜藏(北京)网络科技有限公司');
Define('W_NAME','搜藏网络');
Define('W_CONTACT','盛威');
Define('W_PROVINCE','2');
Define('W_CITY','52');
Define('W_ADRESS','百子湾南二路78号3号楼二层');
Define('W_MOBILE','010-52204565');
Define('W_MAIL','seo@1987214.cn');
Define('W_LOGO','static/upload/images/web3_so_com/logo/logo.png');
Define('W_EDIT','KindEdit');
Define('W_EXPIRYDATE','1487952000');
Define('W_DOMAIN','m.soocang.com');
Define('W_STATUS','0');
Define('W_TIME','');
Define('W_ONLINESELL','10');
Define('W_ONLINEBUY','10');
Define('W_NEXTLINESELL','1');
Define('W_NEXLINEBUY','2');
?>