function __uri(a){return a}function define(a,d){var b={};d.call(this,require,b);TY.widget[a]=b}function require(a){return TY.widget[a]||null}
var Zepto=function(){function a(a){return null==a?""+a:G[O.call(a)]||"object"}function d(E){return"function"==a(E)}function b(a){return null!=a&&a==a.window}function c(a){return null!=a&&a.nodeType==a.DOCUMENT_NODE}function f(E){return"object"==a(E)}function g(a){return f(a)&&!b(a)&&Object.getPrototypeOf(a)==Object.prototype}function h(a){return n.call(a,function(a){return null!=a})}function j(a){return a.replace(/::/g,"/").replace(/([A-Z]+)([A-Z][a-z])/g,"$1_$2").replace(/([a-z\d])([A-Z])/g,"$1_$2").replace(/_/g,
"-").toLowerCase()}function s(a){return a in F?F[a]:F[a]=RegExp("(^|\\s)"+a+"(\\s|$)")}function t(a){return"children"in a?i.call(a.children):e.map(a.childNodes,function(a){return 1==a.nodeType?a:void 0})}function x(a,b,c){for(m in b)c&&(g(b[m])||D(b[m]))?(g(b[m])&&!g(a[m])&&(a[m]={}),D(b[m])&&!D(a[m])&&(a[m]=[]),x(a[m],b[m],c)):b[m]!==l&&(a[m]=b[m])}function r(a,b){return null==b?e(a):e(a).filter(b)}function k(a,b,c,i){return d(b)?b.call(a,c,i):b}function q(a,b,c){null==c?a.removeAttribute(b):a.setAttribute(b,
c)}function u(a,b){var c=a.className,d=c&&c.baseVal!==l;return b===l?d?c.baseVal:c:(d?c.baseVal=b:a.className=b,void 0)}function v(a){var b;try{return a?"true"==a||("false"==a?!1:"null"==a?null:/^0/.test(a)||isNaN(b=Number(a))?/^[\[\{]/.test(a)?e.parseJSON(a):a:b):a}catch(c){return a}}function z(a,b){b(a);for(var c in a.childNodes)z(a.childNodes[c],b)}var l,m,e,p,o,B,y=[],i=y.slice,n=y.filter,A=window.document,C={},F={},J={"column-count":1,columns:1,"font-weight":1,"line-height":1,opacity:1,"z-index":1,
zoom:1},H=/^\s*<(\w+|!)[^>]*>/,P=/^<(\w+)\s*\/?>(?:<\/\1>|)$/,Q=/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([\w:]+)[^>]*)\/>/gi,K=/^(?:body|html)$/i,R=/([A-Z])/g,S="val,css,html,text,data,width,height,offset".split(","),I=A.createElement("table"),L=A.createElement("tr"),M={tr:A.createElement("tbody"),tbody:I,thead:I,tfoot:I,td:L,th:L,"*":A.createElement("div")},T=/complete|loaded|interactive/,U=/^[\w-]*$/,G={},O=G.toString,w={},N=A.createElement("div"),V={tabindex:"tabIndex",readonly:"readOnly",
"for":"htmlFor","class":"className",maxlength:"maxLength",cellspacing:"cellSpacing",cellpadding:"cellPadding",rowspan:"rowSpan",colspan:"colSpan",usemap:"useMap",frameborder:"frameBorder",contenteditable:"contentEditable"},D=Array.isArray||function(a){return a instanceof Array};return w.matches=function(a,b){if(!b||!a||1!==a.nodeType)return!1;var c=a.webkitMatchesSelector||a.mozMatchesSelector||a.oMatchesSelector||a.matchesSelector;if(c)return c.call(a,b);var d,c=a.parentNode,i=!c;return i&&(c=N).appendChild(a),
d=~w.qsa(c,b).indexOf(a),i&&N.removeChild(a),d},o=function(a){return a.replace(/-+(.)?/g,function(a,E){return E?E.toUpperCase():""})},B=function(a){return n.call(a,function(b,c){return a.indexOf(b)==c})},w.fragment=function(a,b,c){var d,n,f;return P.test(a)&&(d=e(A.createElement(RegExp.$1))),d||(a.replace&&(a=a.replace(Q,"<$1></$2>")),b===l&&(b=H.test(a)&&RegExp.$1),b in M||(b="*"),f=M[b],f.innerHTML=""+a,d=e.each(i.call(f.childNodes),function(){f.removeChild(this)})),g(c)&&(n=e(d),e.each(c,function(a,
b){-1<S.indexOf(a)?n[a](b):n.attr(a,b)})),d},w.Z=function(a,b){return a=a||[],a.__proto__=e.fn,a.selector=b||"",a},w.isZ=function(a){return a instanceof w.Z},w.init=function(a,b){var c;if(!a)return w.Z();if("string"==typeof a)if(a=a.trim(),"<"==a[0]&&H.test(a))c=w.fragment(a,RegExp.$1,b),a=null;else{if(b!==l)return e(b).find(a);c=w.qsa(A,a)}else{if(d(a))return e(A).ready(a);if(w.isZ(a))return a;if(D(a))c=h(a);else if(f(a))c=[a],a=null;else if(H.test(a))c=w.fragment(a.trim(),RegExp.$1,b),a=null;else{if(b!==
l)return e(b).find(a);c=w.qsa(A,a)}}return w.Z(c,a)},e=function(a,b){return w.init(a,b)},e.extend=function(a){var b,c=i.call(arguments,1);return"boolean"==typeof a&&(b=a,a=c.shift()),c.forEach(function(c){x(a,c,b)}),a},w.qsa=function(a,b){var d,e="#"==b[0],n=!e&&"."==b[0],f=e||n?b.slice(1):b,l=U.test(f);return c(a)&&l&&e?(d=a.getElementById(f))?[d]:[]:1!==a.nodeType&&9!==a.nodeType?[]:i.call(l&&!e?n?a.getElementsByClassName(f):a.getElementsByTagName(b):a.querySelectorAll(b))},e.contains=function(a,
b){return a!==b&&a.contains(b)},e.type=a,e.isFunction=d,e.isWindow=b,e.isArray=D,e.isPlainObject=g,e.isEmptyObject=function(a){for(var b in a)return!1;return!0},e.inArray=function(a,b,c){return y.indexOf.call(b,a,c)},e.camelCase=o,e.trim=function(a){return null==a?"":String.prototype.trim.call(a)},e.uuid=0,e.support={},e.expr={},e.map=function(a,b){var c,d,i=[];if("number"==typeof a.length)for(d=0;d<a.length;d++)c=b(a[d],d),null!=c&&i.push(c);else for(d in a)c=b(a[d],d),null!=c&&i.push(c);return 0<
i.length?e.fn.concat.apply([],i):i},e.each=function(a,b){var c;if("number"==typeof a.length)for(c=0;c<a.length&&!(!1===b.call(a[c],c,a[c]));c++);else for(c in a)if(!1===b.call(a[c],c,a[c]))break;return a},e.grep=function(a,b){return n.call(a,b)},window.JSON&&(e.parseJSON=JSON.parse),e.each("Boolean,Number,String,Function,Array,Date,RegExp,Object,Error".split(","),function(a,b){G["[object "+b+"]"]=b.toLowerCase()}),e.fn={forEach:y.forEach,reduce:y.reduce,push:y.push,sort:y.sort,indexOf:y.indexOf,concat:y.concat,
map:function(a){return e(e.map(this,function(b,c){return a.call(b,c,b)}))},slice:function(){return e(i.apply(this,arguments))},ready:function(a){return T.test(A.readyState)&&A.body?a(e):A.addEventListener("DOMContentLoaded",function(){a(e)},!1),this},get:function(a){return a===l?i.call(this):this[0<=a?a:a+this.length]},toArray:function(){return this.get()},size:function(){return this.length},remove:function(){return this.each(function(){null!=this.parentNode&&this.parentNode.removeChild(this)})},
each:function(a){return y.every.call(this,function(b,c){return!1!==a.call(b,c,b)}),this},filter:function(a){return d(a)?this.not(this.not(a)):e(n.call(this,function(b){return w.matches(b,a)}))},add:function(a,b){return e(B(this.concat(e(a,b))))},is:function(a){return 0<this.length&&w.matches(this[0],a)},not:function(a){var b=[];if(d(a)&&a.call!==l)this.each(function(c){a.call(this,c)||b.push(this)});else{var c="string"==typeof a?this.filter(a):"number"==typeof a.length&&d(a.item)?i.call(a):e(a);this.forEach(function(a){0>
c.indexOf(a)&&b.push(a)})}return e(b)},has:function(a){return this.filter(function(){return f(a)?e.contains(this,a):e(this).find(a).size()})},eq:function(a){return-1===a?this.slice(a):this.slice(a,+a+1)},first:function(){var a=this[0];return a&&!f(a)?a:e(a)},last:function(){var a=this[this.length-1];return a&&!f(a)?a:e(a)},find:function(a){var b=this;return"object"==typeof a?e(a).filter(function(){var a=this;return y.some.call(b,function(b){return e.contains(b,a)})}):1==this.length?e(w.qsa(this[0],
a)):this.map(function(){return w.qsa(this,a)})},closest:function(a,b){var d=this[0],i=!1;for("object"==typeof a&&(i=e(a));d&&!(i?0<=i.indexOf(d):w.matches(d,a));)d=d!==b&&!c(d)&&d.parentNode;return e(d)},parents:function(a){for(var b=[],d=this;0<d.length;)d=e.map(d,function(a){return(a=a.parentNode)&&!c(a)&&0>b.indexOf(a)?(b.push(a),a):void 0});return r(b,a)},parent:function(a){return r(B(this.pluck("parentNode")),a)},children:function(a){return r(this.map(function(){return t(this)}),a)},contents:function(){return this.map(function(){return i.call(this.childNodes)})},
siblings:function(a){return r(this.map(function(a,b){return n.call(t(b.parentNode),function(a){return a!==b})}),a)},empty:function(){return this.each(function(){this.innerHTML=""})},pluck:function(a){return e.map(this,function(b){return b[a]})},show:function(){return this.each(function(){"none"==this.style.display&&(this.style.display="");if("none"==getComputedStyle(this,"").getPropertyValue("display")){var a=this.style,b;b=this.nodeName;var c,d;b=(C[b]||(c=A.createElement(b),A.body.appendChild(c),
d=getComputedStyle(c,"").getPropertyValue("display"),c.parentNode.removeChild(c),"none"==d&&(d="block"),C[b]=d),C[b]);a.display=b}})},replaceWith:function(a){return this.before(a).remove()},wrap:function(a){var b=d(a);if(this[0]&&!b)var c=e(a).get(0),i=c.parentNode||1<this.length;return this.each(function(d){e(this).wrapAll(b?a.call(this,d):i?c.cloneNode(!0):c)})},wrapAll:function(a){if(this[0]){e(this[0]).before(a=e(a));for(var b;(b=a.children()).length;)a=b.first();e(a).append(this)}return this},
wrapInner:function(a){var b=d(a);return this.each(function(c){var d=e(this),i=d.contents(),c=b?a.call(this,c):a;i.length?i.wrapAll(c):d.append(c)})},unwrap:function(){return this.parent().each(function(){e(this).replaceWith(e(this).children())}),this},clone:function(){return this.map(function(){return this.cloneNode(!0)})},hide:function(){return this.css("display","none")},toggle:function(a){return this.each(function(){var b=e(this);(a===l?"none"==b.css("display"):a)?b.show():b.hide()})},prev:function(a){return e(this.pluck("previousElementSibling")).filter(a||
"*")},next:function(a){return e(this.pluck("nextElementSibling")).filter(a||"*")},html:function(a){return 0===arguments.length?0<this.length?this[0].innerHTML:null:this.each(function(b){var c=this.innerHTML;e(this).empty().append(k(this,a,b,c))})},text:function(a){return 0===arguments.length?0<this.length?this[0].textContent:null:this.each(function(){this.textContent=a===l?"":""+a})},attr:function(a,b){var c;return"string"==typeof a&&b===l?0==this.length||1!==this[0].nodeType?l:"value"==a&&"INPUT"==
this[0].nodeName?this.val():!(c=this[0].getAttribute(a))&&a in this[0]?this[0][a]:c:this.each(function(c){if(1===this.nodeType)if(f(a))for(m in a)q(this,m,a[m]);else q(this,a,k(this,b,c,this.getAttribute(a)))})},removeAttr:function(a){return this.each(function(){1===this.nodeType&&q(this,a)})},prop:function(a,b){return a=V[a]||a,b===l?this[0]&&this[0][a]:this.each(function(c){this[a]=k(this,b,c,this[a])})},data:function(a,b){var c=this.attr("data-"+a.replace(R,"-$1").toLowerCase(),b);return null!==
c?v(c):l},val:function(a){return 0===arguments.length?this[0]&&(this[0].multiple?e(this[0]).find("option").filter(function(){return this.selected}).pluck("value"):this[0].value):this.each(function(b){this.value=k(this,a,b,this.value)})},offset:function(a){if(a)return this.each(function(b){var c=e(this),b=k(this,a,b,c.offset()),d=c.offsetParent().offset(),b={top:b.top-d.top,left:b.left-d.left};"static"==c.css("position")&&(b.position="relative");c.css(b)});if(0==this.length)return null;var b=this[0].getBoundingClientRect();
return{left:b.left+window.pageXOffset,top:b.top+window.pageYOffset,width:Math.round(b.width),height:Math.round(b.height)}},css:function(b,c){if(2>arguments.length){var d=this[0],i=getComputedStyle(d,"");if(!d)return;if("string"==typeof b)return d.style[o(b)]||i.getPropertyValue(b);if(D(b)){var n={};return e.each(D(b)?b:[b],function(a,b){n[b]=d.style[o(b)]||i.getPropertyValue(b)}),n}}var f="";if("string"==a(b))c||0===c?f=j(b)+":"+("number"!=typeof c||J[j(b)]?c:c+"px"):this.each(function(){this.style.removeProperty(j(b))});
else for(m in b)b[m]||0===b[m]?f+=j(m)+":"+("number"!=typeof b[m]||J[j(m)]?b[m]:b[m]+"px")+";":this.each(function(){this.style.removeProperty(j(m))});return this.each(function(){this.style.cssText+=";"+f})},index:function(a){return a?this.indexOf(e(a)[0]):this.parent().children().indexOf(this[0])},hasClass:function(a){return a?y.some.call(this,function(a){return this.test(u(a))},s(a)):!1},addClass:function(a){return a?this.each(function(b){p=[];var c=u(this);k(this,a,b,c).split(/\s+/g).forEach(function(a){e(this).hasClass(a)||
p.push(a)},this);p.length&&u(this,c+(c?" ":"")+p.join(" "))}):this},removeClass:function(a){return this.each(function(b){return a===l?u(this,""):(p=u(this),k(this,a,b,p).split(/\s+/g).forEach(function(a){p=p.replace(s(a)," ")}),u(this,p.trim()),void 0)})},toggleClass:function(a,b){return a?this.each(function(c){var d=e(this);k(this,a,c,u(this)).split(/\s+/g).forEach(function(a){(b===l?!d.hasClass(a):b)?d.addClass(a):d.removeClass(a)})}):this},scrollTop:function(a){if(this.length){var b="scrollTop"in
this[0];return a===l?b?this[0].scrollTop:this[0].pageYOffset:this.each(b?function(){this.scrollTop=a}:function(){this.scrollTo(this.scrollX,a)})}},scrollLeft:function(a){if(this.length){var b="scrollLeft"in this[0];return a===l?b?this[0].scrollLeft:this[0].pageXOffset:this.each(b?function(){this.scrollLeft=a}:function(){this.scrollTo(a,this.scrollY)})}},position:function(){if(this.length){var a=this[0],b=this.offsetParent(),c=this.offset(),d=K.test(b[0].nodeName)?{top:0,left:0}:b.offset();return c.top-=
parseFloat(e(a).css("margin-top"))||0,c.left-=parseFloat(e(a).css("margin-left"))||0,d.top+=parseFloat(e(b[0]).css("border-top-width"))||0,d.left+=parseFloat(e(b[0]).css("border-left-width"))||0,{top:c.top-d.top,left:c.left-d.left}}},offsetParent:function(){return this.map(function(){for(var a=this.offsetParent||A.body;a&&!K.test(a.nodeName)&&"static"==e(a).css("position");)a=a.offsetParent;return a})}},e.fn.detach=e.fn.remove,["width","height"].forEach(function(a){var d=a.replace(/./,function(a){return a[0].toUpperCase()});
e.fn[a]=function(i){var f,n=this[0];return i===l?b(n)?n["inner"+d]:c(n)?n.documentElement["scroll"+d]:(f=this.offset())&&f[a]:this.each(function(b){n=e(this);n.css(a,k(this,i,b,n[a]()))})}}),["after","prepend","before","append"].forEach(function(b,c){var d=c%2;e.fn[b]=function(){var b,i,n=e.map(arguments,function(c){return b=a(c),"object"==b||"array"==b||null==c?c:w.fragment(c)}),f=1<this.length;return 1>n.length?this:this.each(function(a,b){i=d?b:b.parentNode;b=0==c?b.nextSibling:1==c?b.firstChild:
2==c?b:null;n.forEach(function(a){if(f)a=a.cloneNode(!0);else if(!i)return e(a).remove();z(i.insertBefore(a,b),function(a){null==a.nodeName||"SCRIPT"!==a.nodeName.toUpperCase()||a.type&&"text/javascript"!==a.type||a.src||window.eval.call(window,a.innerHTML)})})})};e.fn[d?b+"To":"insert"+(c?"Before":"After")]=function(a){return e(a)[b](this),this}}),w.Z.prototype=e.fn,w.uniq=B,w.deserializeValue=v,e.zepto=w,e}();window.Zepto=Zepto;void 0===window.$&&(window.$=Zepto);
(function(a){function d(a){var c=this.os={},d=this.browser={},g=a.match(/Web[kK]it[\/]{0,1}([\d.]+)/),h=a.match(/(Android);?[\s\/]+([\d.]+)?/),j=!!a.match(/\(Macintosh\; Intel /),s=a.match(/(iPad).*OS\s([\d_]+)/),t=a.match(/(iPod)(.*OS\s([\d_]+))?/),x=!s&&a.match(/(iPhone\sOS)\s([\d_]+)/),r=a.match(/(webOS|hpwOS)[\s\/]([\d.]+)/),k=r&&a.match(/TouchPad/),q=a.match(/Kindle\/([\d.]+)/),u=a.match(/Silk\/([\d._]+)/),v=a.match(/(BlackBerry).*Version\/([\d.]+)/),z=a.match(/(BB10).*Version\/([\d.]+)/),l=
a.match(/(RIM\sTablet\sOS)\s([\d.]+)/),m=a.match(/PlayBook/),e=a.match(/Chrome\/([\d.]+)/)||a.match(/CriOS\/([\d.]+)/),p=a.match(/Firefox\/([\d.]+)/),o=a.match(/MSIE\s([\d.]+)/)||a.match(/Trident\/[\d](?=[^\?]+).*rv:([0-9.].)/),B=!e&&a.match(/(iPhone|iPod|iPad).*AppleWebKit(?!.*Safari)/),y=B||a.match(/Version\/([\d.]+)([^S](Safari)|[^M]*(Mobile)[^S]*(Safari))/);(d.webkit=!!g)&&(d.version=g[1]);h&&(c.android=!0,c.version=h[2]);x&&!t&&(c.ios=c.iphone=!0,c.version=x[2].replace(/_/g,"."));s&&(c.ios=c.ipad=
!0,c.version=s[2].replace(/_/g,"."));t&&(c.ios=c.ipod=!0,c.version=t[3]?t[3].replace(/_/g,"."):null);r&&(c.webos=!0,c.version=r[2]);k&&(c.touchpad=!0);v&&(c.blackberry=!0,c.version=v[2]);z&&(c.bb10=!0,c.version=z[2]);l&&(c.rimtabletos=!0,c.version=l[2]);m&&(d.playbook=!0);q&&(c.kindle=!0,c.version=q[1]);u&&(d.silk=!0,d.version=u[1]);!u&&c.android&&a.match(/Kindle Fire/)&&(d.silk=!0);e&&(d.chrome=!0,d.version=e[1]);p&&(d.firefox=!0,d.version=p[1]);o&&(d.ie=!0,d.version=o[1]);y&&(j||c.ios)&&(d.safari=
!0,j&&(d.version=y[1]));B&&(d.webview=!0);c.tablet=!(!s&&!m&&!(h&&!a.match(/Mobile/)||p&&a.match(/Tablet/)||o&&!a.match(/Phone/)&&a.match(/Touch/)));c.phone=!(c.tablet||c.ipod||!h&&!x&&!r&&!v&&!z&&!(e&&a.match(/Android/)||e&&a.match(/CriOS\/([\d.]+)/)||p&&a.match(/Mobile/)||o&&a.match(/Touch/)))}d.call(a,navigator.userAgent);a.__detect=d})(Zepto);
(function(a){function d(a){return a._zid||(a._zid=t++)}function b(a,b,i,n){if(b=c(b),b.ns)var e=RegExp("(?:^| )"+b.ns.replace(" "," .* ?")+"(?: |$)");return(q[d(a)]||[]).filter(function(a){return!(!a||b.e&&a.e!=b.e||b.ns&&!e.test(a.ns)||i&&d(a.fn)!==d(i)||n&&a.sel!=n)})}function c(a){a=(""+a).split(".");return{e:a[0],ns:a.slice(1).sort().join(" ")}}function f(b,e,i,n,f,g,m){var j=d(b),p=q[j]||(q[j]=[]);e.split(/\s/).forEach(function(d){if("ready"==d)return a(document).ready(i);var e=c(d);e.fn=i;e.sel=
f;e.e in l&&(i=function(b){var c=b.relatedTarget;return!c||c!==this&&!a.contains(this,c)?e.fn.apply(this,arguments):void 0});e.del=g;var y=g||i;e.proxy=function(a){if(a=h(a),!a.isImmediatePropagationStopped()){a.data=n;var c=y.apply(b,a._args==s?[a]:[a].concat(a._args));return!1===c&&(a.preventDefault(),a.stopPropagation()),c}};e.i=p.length;p.push(e);"addEventListener"in b&&b.addEventListener(l[e.e]||v&&z[e.e]||e.e,e.proxy,e.del&&!v&&e.e in z||!!m)})}function g(a,c,i,e,f){var g=d(a);(c||"").split(/\s/).forEach(function(c){b(a,
c,i,e).forEach(function(b){delete q[g][b.i];"removeEventListener"in a&&a.removeEventListener(l[b.e]||v&&z[b.e]||b.e,b.proxy,b.del&&!v&&b.e in z||!!f)})})}function h(b,c){return(c||!b.isDefaultPrevented)&&(c||(c=b),a.each(o,function(a,d){var f=c[a];b[a]=function(){return this[d]=m,f&&f.apply(c,arguments)};b[d]=e}),(c.defaultPrevented!==s?c.defaultPrevented:"returnValue"in c?!1===c.returnValue:c.getPreventDefault&&c.getPreventDefault())&&(b.isDefaultPrevented=m)),b}function j(a){var b,c={originalEvent:a};
for(b in a)p.test(b)||a[b]===s||(c[b]=a[b]);return h(c,a)}var s,t=1,x=Array.prototype.slice,r=a.isFunction,k=function(a){return"string"==typeof a},q={},u={},v="onfocusin"in window,z={focus:"focusin",blur:"focusout"},l={mouseenter:"mouseover",mouseleave:"mouseout"};u.click=u.mousedown=u.mouseup=u.mousemove="MouseEvents";a.event={add:f,remove:g};a.proxy=function(b,c){if(r(b)){var i=function(){return b.apply(c,arguments)};return i._zid=d(b),i}if(k(c))return a.proxy(b[c],b);throw new TypeError("expected function");
};a.fn.bind=function(a,b,c){return this.on(a,b,c)};a.fn.unbind=function(a,b){return this.off(a,b)};a.fn.one=function(a,b,c,d){return this.on(a,b,c,d,1)};var m=function(){return!0},e=function(){return!1},p=/^([A-Z]|returnValue$|layer[XY]$)/,o={preventDefault:"isDefaultPrevented",stopImmediatePropagation:"isImmediatePropagationStopped",stopPropagation:"isPropagationStopped"};a.fn.delegate=function(a,b,c){return this.on(b,a,c)};a.fn.undelegate=function(a,b,c){return this.off(b,a,c)};a.fn.live=function(b,
c){return a(document.body).delegate(this.selector,b,c),this};a.fn.die=function(b,c){return a(document.body).undelegate(this.selector,b,c),this};a.fn.on=function(b,c,d,n,l){var m,h,p=this;return b&&!k(b)?(a.each(b,function(a,b){p.on(a,c,d,b,l)}),p):(k(c)||r(n)||!1===n||(n=d,d=c,c=s),(r(d)||!1===d)&&(n=d,d=s),!1===n&&(n=e),p.each(function(e,p){l&&(m=function(a){return g(p,a.type,n),n.apply(this,arguments)});c&&(h=function(b){var d,i=a(b.target).closest(c,p).get(0);return i&&i!==p?(d=a.extend(j(b),{currentTarget:i,
liveFired:p}),(m||n).apply(i,[d].concat(x.call(arguments,1)))):void 0});f(p,b,n,d,c,h||m)}))};a.fn.off=function(b,c,d){var n=this;return b&&!k(b)?(a.each(b,function(a,b){n.off(a,c,b)}),n):(k(c)||r(d)||!1===d||(d=c,c=s),!1===d&&(d=e),n.each(function(){g(this,b,d,c)}))};a.fn.trigger=function(b,c){return b=k(b)||a.isPlainObject(b)?a.Event(b):h(b),b._args=c,this.each(function(){"dispatchEvent"in this?this.dispatchEvent(b):a(this).triggerHandler(b,c)})};a.fn.triggerHandler=function(c,d){var i,e;return this.each(function(f,
l){i=j(k(c)?a.Event(c):c);i._args=d;i.target=l;a.each(b(l,c.type||c),function(a,b){return e=b.proxy(i),i.isImmediatePropagationStopped()?!1:void 0})}),e};"focusin,focusout,load,resize,scroll,unload,click,dblclick,mousedown,mouseup,mousemove,mouseover,mouseout,mouseenter,mouseleave,change,select,keydown,keypress,keyup,error".split(",").forEach(function(b){a.fn[b]=function(a){return a?this.bind(b,a):this.trigger(b)}});["focus","blur"].forEach(function(b){a.fn[b]=function(a){return a?this.bind(b,a):
this.each(function(){try{this[b]()}catch(a){}}),this}});a.Event=function(a,b){k(a)||(b=a,a=b.type);var c=document.createEvent(u[a]||"Events"),d=!0;if(b)for(var e in b)"bubbles"==e?d=!!b[e]:c[e]=b[e];return c.initEvent(a,d,!0),h(c)}})(Zepto);
(function(a){function d(b,c,d,e){b.global?(b=c||z,d=a.Event(d),e=(a(b).trigger(d,e),!d.isDefaultPrevented())):e=void 0;return e}function b(b){b.global&&0===a.active++&&d(b,null,"ajaxStart")}function c(a,b){var c=b.context;return!1===b.beforeSend.call(c,a,b)||!1===d(b,c,"ajaxBeforeSend",[a,b])?!1:(d(b,c,"ajaxSend",[a,b]),void 0)}function f(a,b,c,e){var f=c.context;c.success.call(f,a,"success",b);e&&e.resolveWith(f,[a,"success",b]);d(c,f,"ajaxSuccess",[b,c,a]);h("success",b,c)}function g(a,b,c,e,f){var l=
e.context;e.error.call(l,c,b,a);f&&f.rejectWith(l,[c,b,a]);d(e,l,"ajaxError",[c,e,a||b]);h(b,c,e)}function h(b,c,e){var f=e.context;e.complete.call(f,c,b);d(e,f,"ajaxComplete",[c,e]);e.global&&!--a.active&&d(e,null,"ajaxStop")}function j(){}function s(a){return a&&(a=a.split(";",2)[0]),a&&(a==o?"html":a==p?"json":m.test(a)?"script":e.test(a)&&"xml")||"text"}function t(a,b){return""==b?a:(a+"&"+b).replace(/[&?]{1,2}/,"?")}function x(b){b.processData&&b.data&&"string"!=a.type(b.data)&&(b.data=a.param(b.data,
b.traditional));!b.data||b.type&&"GET"!=b.type.toUpperCase()||(b.url=t(b.url,b.data),b.data=void 0)}function r(b,c,d,e){return a.isFunction(c)&&(e=d,d=c,c=void 0),a.isFunction(d)||(e=d,d=void 0),{url:b,data:c,success:d,dataType:e}}function k(b,c,d,e){var f,l=a.isArray(c),g=a.isPlainObject(c);a.each(c,function(c,n){f=a.type(n);e&&(c=d?e:e+"["+(g||"object"==f||"array"==f?c:"")+"]");!e&&l?b.add(n.name,n.value):"array"==f||!d&&"object"==f?k(b,n,d,c):b.add(c,n)})}var q,u,v=0,z=window.document,l=/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi,
m=/^(?:text|application)\/javascript/i,e=/^(?:text|application)\/xml/i,p="application/json",o="text/html",B=/^\s*$/;a.active=0;a.ajaxJSONP=function(b,d){if(!("type"in b))return a.ajax(b);var e,l,m=b.jsonpCallback,h=(a.isFunction(m)?m():m)||"jsonp"+ ++v,j=z.createElement("script"),p=window[h],s=function(b){a(j).triggerHandler("error",b||"abort")},t={abort:s};return d&&d.promise(t),a(j).on("load error",function(c,m){clearTimeout(l);a(j).off().remove();"error"!=c.type&&e?f(e[0],t,b,d):g(null,m||"error",
t,b,d);window[h]=p;e&&a.isFunction(p)&&p(e[0]);p=e=void 0}),!1===c(t,b)?(s("abort"),t):(window[h]=function(){e=arguments},j.src=b.url.replace(/\?(.+)=\?/,"?$1="+h),z.head.appendChild(j),0<b.timeout&&(l=setTimeout(function(){s("timeout")},b.timeout)),t)};a.ajaxSettings={type:"GET",beforeSend:j,success:j,error:j,complete:j,context:null,global:!0,xhr:function(){return new window.XMLHttpRequest},accepts:{script:"text/javascript, application/javascript, application/x-javascript",json:p,xml:"application/xml, text/xml",
html:o,text:"text/plain"},crossDomain:!1,timeout:0,processData:!0,cache:!0};a.ajax=function(d){var e=a.extend({},d||{}),l=a.Deferred&&a.Deferred();for(q in a.ajaxSettings)void 0===e[q]&&(e[q]=a.ajaxSettings[q]);b(e);e.crossDomain||(e.crossDomain=/^([\w-]+:)?\/\/([^\/]+)/.test(e.url)&&RegExp.$2!=window.location.host);e.url||(e.url=window.location.toString());x(e);!1===e.cache&&(e.url=t(e.url,"_="+Date.now()));var m=e.dataType,d=/\?.+=\?/.test(e.url);if("jsonp"==m||d)return d||(e.url=t(e.url,e.jsonp?
e.jsonp+"=?":!1===e.jsonp?"":"callback=?")),a.ajaxJSONP(e,l);var h,d=e.accepts[m],p={},k=function(a,b){p[a.toLowerCase()]=[a,b]},r=/^([\w-]+:)\/\//.test(e.url)?RegExp.$1:window.location.protocol,o=e.xhr(),y=o.setRequestHeader;if(l&&l.promise(o),e.crossDomain||k("X-Requested-With","XMLHttpRequest"),k("Accept",d||"*/*"),(d=e.mimeType||d)&&(-1<d.indexOf(",")&&(d=d.split(",",2)[0]),o.overrideMimeType&&o.overrideMimeType(d)),(e.contentType||!1!==e.contentType&&e.data&&"GET"!=e.type.toUpperCase())&&k("Content-Type",
e.contentType||"application/x-www-form-urlencoded"),e.headers)for(u in e.headers)k(u,e.headers[u]);if(o.setRequestHeader=k,o.onreadystatechange=function(){if(4==o.readyState){o.onreadystatechange=j;clearTimeout(h);var b,c=!1;if(200<=o.status&&300>o.status||304==o.status||0==o.status&&"file:"==r){m=m||s(e.mimeType||o.getResponseHeader("content-type"));b=o.responseText;try{"script"==m?(0,eval)(b):"xml"==m?b=o.responseXML:"json"==m&&(b=B.test(b)?null:a.parseJSON(b))}catch(d){c=d}c?g(c,"parsererror",
o,e,l):f(b,o,e,l)}else g(o.statusText||null,o.status?"error":"abort",o,e,l)}},!1===c(o,e))return o.abort(),g(null,"abort",o,e,l),o;if(e.xhrFields)for(u in e.xhrFields)o[u]=e.xhrFields[u];o.open(e.type,e.url,"async"in e?e.async:!0,e.username,e.password);for(u in p)y.apply(o,p[u]);return 0<e.timeout&&(h=setTimeout(function(){o.onreadystatechange=j;o.abort();g(null,"timeout",o,e,l)},e.timeout)),o.send(e.data?e.data:null),o};a.get=function(){return a.ajax(r.apply(null,arguments))};a.post=function(){var b=
r.apply(null,arguments);return b.type="POST",a.ajax(b)};a.getJSON=function(){var b=r.apply(null,arguments);return b.dataType="json",a.ajax(b)};a.fn.load=function(b,c,d){if(!this.length)return this;var e,f=this,m=b.split(/\s/),b=r(b,c,d),g=b.success;return 1<m.length&&(b.url=m[0],e=m[1]),b.success=function(b){f.html(e?a("<div>").html(b.replace(l,"")).find(e):b);g&&g.apply(f,arguments)},a.ajax(b),this};var y=encodeURIComponent;a.param=function(a,b){var c=[];return c.add=function(a,b){this.push(y(a)+
"="+y(b))},k(c,a,b),c.join("&").replace(/%20/g,"+")}})(Zepto);
(function(a){a.fn.serializeArray=function(){var d,b=[];return a([].slice.call(this.get(0).elements)).each(function(){d=a(this);var c=d.attr("type");"fieldset"!=this.nodeName.toLowerCase()&&!this.disabled&&"submit"!=c&&"reset"!=c&&"button"!=c&&("radio"!=c&&"checkbox"!=c||this.checked)&&b.push({name:d.attr("name"),value:d.val()})}),b};a.fn.serialize=function(){var a=[];return this.serializeArray().forEach(function(b){a.push(encodeURIComponent(b.name)+"="+encodeURIComponent(b.value))}),a.join("&")};
a.fn.submit=function(d){d?this.bind("submit",d):this.length&&(d=a.Event("submit"),this.eq(0).trigger(d),d.isDefaultPrevented()||this.get(0).submit());return this}})(Zepto);
(function(a,d){var b,c,f,g,h,j,s,t,x,r,k="",q=window.document.createElement("div"),u=/^((translate|rotate|scale)(X|Y|Z|3d)?|matrix(3d)?|perspective|skew(X|Y)?)$/i,v={};a.each({Webkit:"webkit",Moz:"",O:"o"},function(a,c){return q.style[a+"TransitionProperty"]!==d?(k="-"+a.toLowerCase()+"-",b=c,!1):void 0});c=k+"transform";v[f=k+"transition-property"]=v[g=k+"transition-duration"]=v[j=k+"transition-delay"]=v[h=k+"transition-timing-function"]=v[s=k+"animation-name"]=v[t=k+"animation-duration"]=v[r=k+
"animation-delay"]=v[x=k+"animation-timing-function"]="";a.fx={off:b===d&&q.style.transitionProperty===d,speeds:{_default:400,fast:200,slow:600},cssPrefix:k,transitionEnd:b?b+"TransitionEnd":"transitionend",animationEnd:b?b+"AnimationEnd":"animationend"};a.fn.animate=function(b,c,f,e,g){return a.isFunction(c)&&(e=c,f=d,c=d),a.isFunction(f)&&(e=f,f=d),a.isPlainObject(c)&&(f=c.easing,e=c.complete,g=c.delay,c=c.duration),c&&(c=("number"==typeof c?c:a.fx.speeds[c]||a.fx.speeds._default)/1E3),g&&(g=parseFloat(g)/
1E3),this.anim(b,c,f,e,g)};a.fn.anim=function(b,l,m,e,p){var o,k,q,i={},n="",A=this,C=a.fx.transitionEnd,F=!1;if(l===d&&(l=a.fx.speeds._default/1E3),p===d&&(p=0),a.fx.off&&(l=0),"string"==typeof b)i[s]=b,i[t]=l+"s",i[r]=p+"s",i[x]=m||"linear",C=a.fx.animationEnd;else{k=[];for(o in b)u.test(o)?n+=o+"("+b[o]+") ":(i[o]=b[o],k.push(o.replace(/([a-z])([A-Z])/,"$1-$2").toLowerCase()));n&&(i[c]=n,k.push(c));0<l&&"object"==typeof b&&(i[f]=k.join(", "),i[g]=l+"s",i[j]=p+"s",i[h]=m||"linear")}return q=function(b){if("undefined"!=
typeof b){if(b.target!==b.currentTarget)return;a(b.target).unbind(C,q)}else a(this).unbind(C,q);F=!0;a(this).css(v);e&&e.call(this)},0<l&&(this.bind(C,q),setTimeout(function(){F||q.call(A)},1E3*l+25)),this.size()&&this.get(0),this.css(i),0>=l&&setTimeout(function(){A.each(function(){q.call(this)})},0),this};q=null})(Zepto);window.Zepto=Zepto;"$"in window||(window.$=Zepto);window.jQuery=Zepto;
!function(a){a.extend(a,{contains:function(a,b){return a.compareDocumentPosition?!!(16&a.compareDocumentPosition(b)):a!==b&&a.contains(b)}})}(Zepto);
(function(a,d){a.extend(a,{toString:function(a){return Object.prototype.toString.call(a)},slice:function(a,b){return Array.prototype.slice.call(a,b||0)},later:function(a,b,d,h,j){return window["set"+(d?"Interval":"Timeout")](function(){a.apply(h,j)},b||0)},parseTpl:function(a,b){var d="var __p=[],print=function(){__p.push.apply(__p,arguments);};with(obj||{}){__p.push('"+a.replace(/\\/g,"\\\\").replace(/'/g,"\\'").replace(/<%=([\s\S]+?)%>/g,function(a,b){return"',"+b.replace(/\\'/g,"'")+",'"}).replace(/<%([\s\S]+?)%>/g,
function(a,b){return"');"+b.replace(/\\'/g,"'").replace(/[\r\n\t]/g," ")+"__p.push('"}).replace(/\r/g,"\\r").replace(/\n/g,"\\n").replace(/\t/g,"\\t")+"');}return __p.join('');",d=new Function("obj",d);return b?d(b):d},throttle:function(b,f,g){function h(){function a(){s=Date.now();f.apply(r,q)}function h(){j=d}var r=this,k=Date.now()-s,q=arguments;g&&!j&&a();j&&clearTimeout(j);g===d&&k>b?a():j=setTimeout(g?h:a,g===d?b-k:b)}var j,s=0;return"function"!=typeof f&&(g=f,f=b,b=250),h._zid=f._zid=f._zid||
a.proxy(f)._zid,h},debounce:function(b,f,g){return f===d?a.throttle(250,b,!1):a.throttle(b,f,g===d?!1:!1!==g)}});a.each("String,Boolean,RegExp,Number,Date,Object,Null,Undefined".split(","),function(c,f){var g;if(!("is"+f in a)){switch(f){case "Null":g=function(a){return null===a};break;case "Undefined":g=function(a){return a===d};break;default:g=function(a){return RegExp(f+"]","i").test(b(a))}}a["is"+f]=g}});var b=a.toString})(Zepto);
(function(a){var d=navigator.userAgent,b=navigator.appVersion,c=a.browser;a.extend(c,{qq:/qq/i.test(d),uc:/UC/i.test(d)||/UC/i.test(b)});c.uc=c.uc||!c.qq&&!c.chrome&&!c.firefox&&!/safari/i.test(d);try{c.version=c.uc?b.match(/UC(?:Browser)?\/([\d.]+)/)[1]:c.qq?d.match(/MQQBrowser\/([\d.]+)/)[1]:c.version}catch(f){}a.support=a.extend(a.support||{},{orientation:!(c.uc||5>parseFloat(a.os.version)&&(c.qq||c.chrome))&&!(a.os.android&&3<parseFloat(a.os.version))&&"orientation"in window&&"onorientationchange"in
window,touch:"ontouchend"in document,cssTransitions:"WebKitTransitionEvent"in window,has3d:"WebKitCSSMatrix"in window&&"m11"in new WebKitCSSMatrix})})(Zepto);
(function(a){function d(){a(window).on("scroll",a.debounce(80,function(){a(document).trigger("scrollStop")},!1))}function b(){a(window).off("scroll");d()}a(document).ready(function(){var b,d,g=function(){var a=document.documentElement;return 1.1>a.clientWidth/Math.max(a.clientHeight,320)?"portrait":"landscape"},h=g();a(window).bind(a.support.orientation?"orientationchange":"resize",a.debounce(function(){d=20;clearInterval(b);b=a.later(function(){var j=g();h!==j?(h=j,clearInterval(b),a(window).trigger("ortchange")):
--d&&clearInterval(b)},50,!0)}))});d();a(window).on("pageshow",function(c){c.persisted&&a(document).off("touchstart",b).one("touchstart",b)})})(Zepto);var TY=TY||{};!function(){var a=TY;TY=jQuery.noConflict?jQuery.noConflict():jQuery;TY.extend(TY,a);TY.extend(TY,{version:"1.0",debug:"release",isDebuger:function(){return"http://static.tianyaui.com/global/ty2.0/core/core_interface.js".replace("/core/core_interface.js","")}})}();
TY.extend(TY,{ns:function(a,d){for(var b=a.split("."),c=window,f=0;f<b.length;f++)c[b[f]]||(c[b[f]]=f==b.length-1&&d?d:{}),c=c[b[f]];return c},namespace:function(){var a,d,b,c=arguments,f=null;if(1==c[c.length-1])for(a=0;a<c.length-1;++a)for(b=c[a].split("."),f=TY,d="TY"==b[0]?1:0;d<b.length;++d)f[b[d]]=f[b[d]]||{},f=f[b[d]];else for(a=0;a<c.length;++a)for(b=c[a].split("."),f=TY,d="TY"==b[0]?1:0;d<b.length;++d)f[b[d]]=f[b[d]]||{},f=f[b[d]];return f}});
TY.console={log:function(a){"undefined"==typeof console||"debuger"!=TY.debug&&"@debugState@"!=TY.debug||console.log(a)}};(function(){try{var a=null,d=0;if(a=navigator.userAgent.toLowerCase().match(/msie ([\d.]+)/),d=a?parseInt(a[1],10):0,6==d)try{document.execCommand("BackgroundImageCache",!1,!0)}catch(b){}}catch(c){}})();String.prototype.TY_trim=function(a){return a=a||/(^\s+)|(\s+$)/g,this.replace(a,"")};
String.prototype.TY_format=function(){var a=arguments,d=1==a.length&&"object"==typeof a[0]?a[0]:a;return this.replace(/\{([\d\w]+)\}/g,function(a,c){return void 0!=d[c]?d[c].toString():""})};String.prototype.TY_toJson=function(a,d,b){b=TY.isFunction(b)?b:function(a){return a};a=a||"&";d=d||"=";for(var a=this.split(a),c=[],f=0,g=a.length;g>f;f++)""!=a[f].trim(),c.push(a[f]);var h={};return TY.each(c,function(a,c){var f=c.split(d);void 0!=f[1]&&(h[f[0]]=b(f[1]))}),h};
String.prototype.TY_html=function(a){var d="&,&amp;,<,&lt;,>,&gt;, ,&nbsp;,\",&quot;,',&#039;,\\r,<br>,\\n,<br>,/,&#047;,\\\\,&#092;".split(",");a&&d.reverse();for(var a=0,b=this;a<d.length;a+=2)b=b.replace(RegExp(d[a],"g"),d[1+a]);return b};String.prototype.TY_CNLength=function(a){for(var a=a||2,d=0,b=0,c=this.length;c>b;b++)127<this.charCodeAt(b)?d+=a:d++;return d};String.prototype.TY_removeTag=function(){return this.replace(/<(\w+)[^>]*\/?>([^<]*)(?:<\/\1>|)/g,"$2")};
String.prototype.ltrim=function(){return this.TY_trim(/^(\s*)/,"")};String.prototype.rtrim=function(){return this.TY_trim(/\s*$/,"")};String.prototype.leftFix=function(a,d){for(var b=this;b.length<d;)b=a+b;return b};String.prototype.getCNlen=function(){return this.TY_CNLength(2)};
String.prototype.subStringCn=function(a,d,b){var c,f=0,g=this,h="..",b=b||2;d&&(!0===d?(a-=b,d=h):"string"==TY.type(d)&&(h=d.TY_removeTag(),c=h.TY_CNLength(b),a-=c));for(c=0;c<g.length;c++)if(f+=127<g.charCodeAt(c)?b:1,f>a){g=g.slice(0,c);d&&(g+=d);break}return g.toString()};String.prototype.encodeTag=function(){return this.TY_html()};String.prototype.trim=function(){return this.TY_trim()};
Date.prototype.TY_format=function(){var a=arguments;if(1==a.length&&"string"==typeof a[0]){var a=a[0],d={yyyy:this.getFullYear(),yy:this.getFullYear().toString().match(/\d{2}$/),mm:10>this.getMonth()+1?"0"+(this.getMonth()+1):this.getMonth()+1,m:this.getMonth()+1,dd:10>this.getDate()?"0"+this.getDate():this.getDate(),d:this.getDate(),hh:10>this.getHours()?"0"+this.getHours():this.getHours(),h:this.getHours(),MM:10>this.getMinutes()?"0"+this.getMinutes():this.getMinutes(),M:this.getMinutes(),ss:10>
this.getSeconds()?"0"+this.getSeconds():this.getSeconds(),s:this.getSeconds(),w:this.getDay()+1,W:"日,一,二,三,四,五,六".split(",")[this.getDay()]};return a=a.replace(/(yyyy|yy|mm|m|dd|d|hh|h|MM|M|ss|s|w|W)/gi,function(a,c){return d[c]})}};Array.prototype.TY_indexOf=function(a,d){var b=d||0;if(Array.prototype.indexOf)return this.indexOf(a,b);for(var c=this.length,b=b?0>b?Math.max(0,c+b):b:0;c>b;b++)if(b in this&&this[b]===a)return b;return-1};
TY.browser&&TY.browser.msie&&(Array.prototype.indexOf=function(a,d){for(var b=d||0,c=this.length,b=b?0>b?Math.max(0,c+b):b:0;c>b;b++)if(b in this&&this[b]===a)return b;return-1});Array.prototype.TY_unique=function(a){var d=1,a=a?this.slice(0):this;for(a.sort();a[d];d++)a[d]==a[d-1]&&a.splice(d--,1);return a};Array.prototype.TY_remove=function(a,d){for(var b=d?this.slice(0):this,c=0,f=b.length;f>c;c++)a==b[c]&&(b.splice(c--,1),f--);return b};Array.prototype.uniq=function(){return this.TY_unique()};
Array.prototype.remove=function(a){this.splice(this.indexOf(a),1)};TY.param=TY.param||{};
TY.extend(TY.param,{getHrefParam:function(a){var a=a||location.href,d=a.indexOf("?"),b=a.indexOf("#");return-1!=b&&(a=a.substring(0,b)),a.substring(d+1).TY_toJson("&","=",function(a){try{return decodeURIComponent(a)}catch(b){}})},getHashParam:function(a){var a=a||location.href,d=a.indexOf("#");return a.substring(d+1).TY_toJson("&","=",function(a){try{return decodeURIComponent(a)}catch(c){}})},makeJson2Str:function(a,d,b,c){var f=[];d=d||"&";b=b||"=";c=TY.isFunction(c)?c:function(a){return a};for(var g in a)f.push(g+
b+c(a[g]));return f.join(d)},makeStr2Json:function(a,d,b,c){return a.TY_toJson(d,b,c)},URI:function(a){if("string"!==TY.type(a))return null;1>a.indexOf("://")&&(a=location.protocol+"//"+location.host+(0==a.indexOf("/")?"":location.pathname.substr(0,location.pathname.lastIndexOf("/")+1))+a);var d=a.split("://"),b={};if("array"==TY.type(d)&&1<d.length&&/^[a-zA-Z]+$/.test(d[0])){b.protocol=d[0].toLowerCase();var c=d[1].split("/");if("array"==TY.type(c))return b.host=c[0],b.pathname="/"+c.slice(1).join("/").replace(/(\?|\#).+/i,
""),b.href=a,a=d[1].lastIndexOf("?"),c=d[1].lastIndexOf("#"),b.search=0<=a?d[1].substring(a):"",b.hash=0<=c?d[1].substring(c):"",0<b.search.length&&0<b.hash.length&&(b.search=a>c?"":d[1].substring(a,c)),b}return null}});TY.cookie={};
TY.extend(TY.cookie,{domain:function(){return document.domain},set:function(a,d,b,c,f,g){if(f){var h=new Date;h.setTime((new Date).getTime()+864E5*f)}return document.cookie=a+"="+d+"; "+(f?"expires="+h.toGMTString()+"; ":"")+(c?"path="+c+"; ":"path=/; ")+(b?"domain="+b+";":"domain="+this.domain()+";")+(g?"; secure":""),!0},get:function(a){return(a=document.cookie.match(RegExp("(?:^|;+|\\s+)"+a+"=([^;]*)")))?a[1]:null},del:function(a,d,b){document.cookie=a+"=; expires=Mon, 26 Jul 1997 05:00:00 GMT; "+
(b?"path="+b+"; ":"path=/; ")+(d?"domain="+d+";":"domain="+this.domain()+";")},setPart:function(a,d,b,c,f,g,h){var j=(this.get(a)||"").TY_toJson();j[d]=b;this.set(a,TY.param.makeJson2Str(j),c,f,g,h)},getPart:function(a,d){var b=this.get(a),b=b?b.TY_toJson():{};return"undefined"!=typeof b[d]?b[d]:null}});-1!=document.domain.indexOf("tianya.cn")&&(document.domain="tianya.cn");
var __global={cityNames:"北京,上海,天津,重庆,石家庄,保定,唐山,太原,大同,晋城,呼和浩特,包头,沈阳,大连,长春,四平,吉林,哈尔滨,佳木斯,南京,苏州,扬州,无锡,徐州,杭州,温州,绍兴,宁波,合肥,芜湖,安庆,马鞍山,福州,厦门,泉州,南昌,景德镇,赣州,九江,济南,青岛,淄博,威海,郑州,开封,洛阳,安阳,南阳,武汉,宜昌,襄樊,长沙,株洲,常德,岳阳,广州,深圳,佛山,潮州,东莞,南宁,柳州,桂林,海口,三亚,儋州,文昌,乐东,五指山,琼海,万宁,定安,昌江,临高,澄迈,东方,陵水,保亭,屯昌,琼中,白沙,成都,自贡,绵阳,乐山,贵阳,遵义,六盘水,昆明,拉萨,西安,宝鸡,咸阳,兰州,天水,乌鲁木齐,台湾,香港,澳门,西宁,银川,张家口,秦皇岛,沧州,邢台,承德,廊坊,邯郸,衡水,长治,运城,朔州,晋中,吕梁,临汾,忻州,阳泉,通辽,鄂尔多斯,呼伦贝尔,巴彦淖尔市,乌海,兴安盟,赤峰,阿拉善盟,锡林郭勒盟,乌兰察布市,朝阳,本溪,抚顺,鞍山,盘锦,铁岭,锦州,葫芦岛,丹东,阜新,营口,辽阳,通化,白山,延边朝鲜族自治州,辽源,松原,白城,齐齐哈尔,绥化,大兴安岭地区,伊春,鹤岗,双鸭山,黑河,鸡西,大庆,牡丹江,七台河,常州,连云港,南通,盐城,宿迁,泰州,镇江,淮安,丽水,衢州,舟山,台州,湖州,嘉兴,金华,淮北,淮南,亳州,池州,六安,阜阳,蚌埠,滁州,铜陵,宿州,黄山,宣城,巢湖,南平,漳州,龙岩,宁德,莆田,三明,吉安,宜春,抚州,新余,萍乡,上饶,鹰潭,德州,莱芜,聊城,枣庄,潍坊,泰安,东营,烟台,临沂,日照,滨州,荷泽,济宁,许昌,三门峡,平顶山,驻马店,周口,濮阳,鹤壁,济源,焦作,商丘,漯河,新乡,信阳,鄂州,咸宁,孝感,荆州,十堰,黄冈,黄石,恩施土家族苗族自治州,荆门,随州,益阳,永州,郴州,湘西土家族苗族自治州,邵阳,怀化,娄底,湘潭,张家界,衡阳,清远,河源,揭阳,汕头,珠海,肇庆,梅州,中山,云浮,江门,惠州,茂名,韶关,汕尾,湛江,阳江,河池,崇左,钦州,玉林,梧州,贺州,贵港,北海,防城港,百色,来宾,雅安,凉山彝族自治州,宜宾,泸州,资阳,阿坝藏族羌族自治州,甘孜藏族自治州,德阳,攀枝花,广元,内江,巴中,眉山,达州,南充,遂宁,广安,毕节,黔南布依族苗族自治州,黔东南苗族侗族自治州,黔西南布依族苗族自治州,铜仁,安顺,迪庆藏族自治州,文山壮族苗族自治州,德宏德宏傣族景颇族自治州,临沧,玉溪,西双版纳傣族自治州,楚雄彝族自治州,思茅,保山,昭通,曲靖,红河哈尼族彝族自治州,大理大理白族自治州,怒江傈僳族自治州,丽江,日喀则,林芝,阿里,那曲,昌都,山南,榆林,渭南,安康,汉中,商洛,铜川,延安,白银,庆阳,金昌,武威,陇南,甘南藏族自治州,酒泉,张掖,临夏回族自治州,平凉,定西,海西蒙古族藏族自治州,玉树藏族自治州,果洛藏族自治州,海南藏族自治州,海北藏族自治州,黄南藏族自治州,海东,石嘴山,固原,吴忠,阿克苏,塔城,伊犁哈萨克自治州,阿勒泰,巴音郭楞蒙古自治州,克孜勒苏柯尔克孜自治州,克拉玛依,石河子,昌吉回族自治州,伊犁哈萨克自治州,喀什,和田,哈密,博尔塔拉蒙古自治州,吐鲁番,伊吾,顺德".split(","),setCookie:function(a,
d,b,c,f,g){null===d?__global.setCookieNoEscape(a,null,b,c,f,g):__global.setCookieNoEscape(a,escape(d),b,c,f,g)},setCookieNoEscape:function(a,d,b,c,f,g){TY.cookie.set(a,d,f,c,b,g)},setPartCookieNoEscape:function(a,d,b,c,f,g,h){return TY.cookie.setPart(a,d,b,g,f,c,h),null},getCookie:function(a){return unescape(TY.cookie.get(a))||null},setPartCookie:function(a,d,b,c,f,g,h){return TY.cookie.setPart(a,d,escape(b),g,f,c,h),null},getPartCookie:function(a,d){return unescape(TY.cookie.getPart(a,d))||null},
getParameter:function(a){for(var d=document.getElementsByTagName("script"),b=d.length,c=0;b>c;c++)if(d[c].src&&d[c].src.match(/global\.js(\?.*)?$/)){var f=RegExp("(^|)"+a+"=([^&]*)(&|$)","gi").exec(d[c].src);if(f)return f[2]}return null},getUserCityId:function(){return this.getCookie("__cid")},getUserCityName:function(){var a=this.getCookie("__cid");return!isNaN(a)&&1<=a&&a<=this.cityNames.length?this.cityNames[a-1]:null},getUserName:function(){return null==this.getCookie("user")?null:this.getPartCookie("user",
"w")},getUserId:function(){return null==this.getCookie("user")?null:this.getPartCookie("user","id")},getKey:function(){return null==this.getCookie("temp")?null:this.getPartCookie("temp","k")},getSysGrad:function(){return null==this.getCookie("temp")?null:this.getPartCookie("temp","s")},getCookieTempTime:function(){return null==this.getCookie("temp")?1E9:this.getPartCookie("temp","t")},getCookieCheckKey:function(){return null==this.getCookie("temp")?null:this.getPartCookie("temp","b")},getCookieCstmTime:function(){return this.getCookie("time")?
this.getPartCookie("time","ct"):null},setCookieCstmTime:function(a){this.updatePartCookie("time","ct",a)},isOnline:function(){return this._isOnline=!1,this._cookieTempTime=this.getCookieTempTime(),-1!=this._cookieTempTime&&!isNaN(this.getUserId())&&0<this.getUserId()&&!isNaN(this.getKey())&&0<this.getKey()&&(this._isOnline=!0),this._isOnline},IsLoadReadCookieFile:!0,refreshCookie:function(){var a=this.getCookieCstmTime(),d=(new Date).getTime()/1E3;a&&7200<d-a&&document.write('<script charset="utf-8" src="http://passport.tianya.cn/refresh.jsp?loginFrom='+
encodeURIComponent(window.location.href)+'"><\/script>');this.setCookieCstmTime(d)},updatePartCookie:function(a,d,b){this.setPartCookieNoEscape(a,d,b,this.getCookieDaysLeft(),"/",this.getRootDomain(),!1)},getRootDomain:function(){var a=document.domain.split(".");return"."+a[a.length-2]+"."+a[a.length-1]},getCookieDaysLeft:function(){var a=this.getPartCookie("time","et");return a&&(-1==a||(new Date).getTime()),30}};__global.refreshCookie();
(function(){try{var a=null,d=0;if(a=navigator.userAgent.toLowerCase().match(/msie ([\d.]+)/),d=a?parseInt(a[1],10):0,6==d)try{document.execCommand("BackgroundImageCache",!1,!0)}catch(b){}}catch(c){}})();
TY.crossSender=function(){function a(a,b,c,d){var f=document.createElement("iframe");return f.id=f.name=b,f.style.width=f.style.height="0",f.style.display="none",f.src=c,d&&(f.proxyReady=function(){d(f)}),a.appendChild(f),f}function d(a,b){var a="string"==typeof a?document.getElementById(a):a,c=[],d;for(d in b)c.push('<input type="hidden" value="'+b[d]+'" name="'+d+'" />');a.innerHTML=c.join("")}var b={},c=0,f="_fp_frm_",g="form_";return b.ajax=function(b){var c=b.onSuccess||function(){},d=b.url,
f=TY.param.URI(d),g="proxy_cajax_ifm_"+f.host;b.onSuccess=function(a){var d=a.responseText,f=d;switch(b.dataType){case "script":d=d.replace(/<script (type="text\/javascript")?>/g,"").replace(/<\/script>/g,"");eval("ret="+d.substr(d.indexOf("=")+1));break;case "jsonp":var g=d.indexOf("("),l=d.lastIndexOf(")"),d=d.substr(g+1,l-g-1);case "json":try{f=JSON.parse(d)}catch(m){eval("ret ="+d)}break;default:f=d}c(f,a)};var r=document.getElementById(g),k=function(){if("undefined"==typeof r.contentWindow||
"undefined"==typeof r.contentWindow.ajax)return window.setTimeout(arguments.callee,100),void 0;if("object"==typeof b.data){var a=TY.param.makeJson2Str(b.data);"POST"==b.method?b.data=a:d+=(-1<d.indexOf("?")?"&":"?")+a}r.contentWindow.ajax(d,b)};r?k():r=a(document.body,g,f.protocol+"://"+f.host+"/ajax_proxy.html",k)},b.form=function(b){function j(a){var b=document.createElement("form");b.action=s;b.name=b.id=g+c;b.method=x||"POST";b.enctype="multipart/form-data";d(b,t);r&&(b.target=f+c,a.callback=
function(c){r(c);TY(b).remove();TY(a).remove()});k.appendChild(b);b.submit()}var s=b.url,t=b.data||{},x=b.method||"POST",r=b.onSuccess||null,k=document.getElementById("_ifm_for_div");k||(k=document.createElement("div"),k.id="_ifm_for_div",document.body.appendChild(k));b=++c;b=f+b;return r?a(k,b,"/form_proxy.html",j):j(),c},b}();TY=TY||{};
!function(){if(!TY.Deferred){var a="done,fail,isResolved,isRejected,promise,then,always,pipe".split(","),d=[].slice,b={};b.extend=TY.extend||function(a,b){var a=a||{},d;for(d in b)"undefined"==typeof a[d]&&(a[d]=b[d])};TY.extend2=b.extend;b.extend(b,{type:TY.type||function(a){return null===a?"null":void 0===a?"undefined":Object.prototype.toString.call(a).slice(8,-1).toLowerCase()},isFunction:TY.isFunction||function(a){return"function"===jQuery.type(a)},each:TY.each||function(a,b){for(name in a)b.call(a[name],
name,a[name])}});TY.type=b.type;b.extend(TY,{_Deferred:function(){var a,d,g,h=[],j={done:function(){if(!g){var d,f,x,r,k,q=arguments;for(a&&(k=a,a=0),d=0,f=q.length;f>d;d++)x=q[d],r=b.type(x),"array"===r?j.done.apply(j,x):"function"===r&&h.push(x);k&&j.resolveWith(k[0],k[1])}return this},resolveWith:function(b,j){if(!g&&!a&&!d){j=j||[];d=1;try{for(;h[0];)h.shift().apply(b,j)}finally{a=[b,j],d=0}}return this},resolve:function(){return j.resolveWith(this,arguments),this},isResolved:function(){return!(!d&&
!a)},cancel:function(){return g=1,h=[],this}};return j},Deferred:function(c){var d,g=TY._Deferred(),h=TY._Deferred();return b.extend(g,{then:function(a,b){return g.done(a).fail(b),this},always:function(){return g.done.apply(g,arguments).fail.apply(this,arguments)},fail:h.done,rejectWith:h.resolveWith,reject:h.resolve,isRejected:h.isResolved,pipe:function(a,c){return TY.Deferred(function(d){b.each({done:[a,"resolve"],fail:[c,"reject"]},function(a,c){var f,h=c[0],j=c[1];b.isFunction(h)?g[a](function(){f=
h.apply(this,arguments);f&&b.isFunction(f.promise)?f.promise().then(d.resolve,d.reject):d[j+"With"](this===g?d:this,[f])}):g[a](d[j])})}).promise()},promise:function(b){if(null==b){if(d)return d;d=b={}}for(var c=a.length;c--;)b[a[c]]=g[a[c]];return b}}),g.done(h.cancel).fail(g.cancel),delete g.cancel,c&&c.call(g,g),g},when:function(a){function f(a){return function(b){g[a]=1<arguments.length?d.call(arguments,0):b;--s||t.resolveWith(t,d.call(g,0))}}var g=arguments,h=0,j=g.length,s=j,t=1>=j&&a&&b.isFunction(a.promise)?
a:TY.Deferred();if(1<j){for(;j>h;h++)g[h]&&b.isFunction(g[h].promise)?g[h].promise().then(f(h),t.reject):--s;s||t.resolveWith(t,g)}else t!==a&&t.resolveWith(t,j?[a]:[]);return t.promise()}})}}();
TY.module=function(){function a(a,b){return TY.Deferred(function(c){var d=document.createElement("script");d.type="text/javascript";b&&(d.charset=b);d.src=a;v.appendChild(d);d.onload=d.onreadystatechange=function(){this.readyState&&"loaded"!==this.readyState&&"complete"!==this.readyState||(q[a].loaded=!0,c.resolve())}}).promise()}function d(a,b){return TY.Deferred(function(c){var d=document.createElement("link");d.type="text/css";d.rel="stylesheet";b&&(d.charset=b);d.href=a;v.appendChild(d);c.resolve()}).promise()}
function b(b,c,e){return c=c||b.toLowerCase().substring(b.lastIndexOf(".")+1),"undefined"==typeof q[b]&&(q[b]={path:b,type:c,charset:e}),k[b]||(k[b]=0==c.indexOf("css")?d(b,e):a(b,e)),k[b]}function c(a,b,c){b=b||[];c=c||{};c[a]=!0;var d;if("undefined"!=typeof q[a]&&(d=q[a].rely))for(var f=0,g=d.length;g>f;f++)!0!==c[d[f]]&&arguments.callee(d[f],b,c);b.push(a);return b}function f(a){for(var c,d,f,g,h=0,j=a.length,i=TY.Deferred(),k=0;j>k;k++)d=a[k],f="",g="",(c=q[d]||null)&&(d=c.path,f=c.type,g=c.charset),
b(d,f,g).then(function(){++h==j&&i.resolve()},function(){i.reject()});return i.promise()}function g(a){function c(g){var m=a[g];(f=q[m]||null)&&(m=f.path);b(m,"","").then(function(){d(!0,g)},function(){d(!1,g)})}function d(a,b){a?++b<g?c(b):h.resolve():h.reject()}var f,g=a.length,h=TY.Deferred();return c(0),h.promise()}function h(a,c){var d=!1;b(a).done(function(){d=!0;c(!0)});setTimeout(function(){d||c(!1)},u)}function j(a,b,c){var d=!1,a=c?g(a):f(a);TY.when(a).done(function(){d=!0;b(!0)}).fail(function(){d=
!1;b(!1)});setTimeout(function(){d||b(!1)},u)}function s(a,b){if("undefined"==typeof q[a])return b(!1),void 0;if(TY.module.isLoadedInterface(a))return b(!0),void 0;var d=c(a);j(d,b,!0)}function t(a,b){function c(a){a?++d==f&&b(!0):b(!1)}for(var d=0,f=a.length,g=0;f>g;g++)s(a[g],c)}function x(a,b){function c(f,g){f?d>g?s(a[g],function(a){c(a,++g)}):b(!0):b(!1)}var d=a.length;c(!0,0)}function r(a,b,c){a.length;c?x(a,b):t(a,b)}var k={},q={},u=1E4,v=document.head||document.getElementsByTagName("head")[0],
z={add:function(a,b){q[a]=b},loadInterface:function(a,b,c,d){u=d||u;b=b||function(){};"string"==TY.type(a)?s(a,b,!0):"array"==TY.type(a)?r(a,b,c):b(!1)},loadUrl:function(a,b,c,d){u=d||u;"string"==TY.type(a)?h(a,b):"array"==TY.type(a)&&j(a,b,c)},getInterface:function(){return q},loadedInterface:function(a){var b=q;"undefined"==typeof b[a]&&(b[a]={});b[a].loaded=!0},isLoadedInterface:function(a){var b=q;return"undefined"!=typeof b[a]&&b[a].loaded?!0:!1},registerInterface:function(a,b,c){var d,f,g,h=
(new Date).getTime()/1E3,i;for(i in a)f=parseInt(a[i].cache||null,10),d=c+a[i].path,g=i.split("."),1<g&&"TY"==g[0]&&"undefined"==typeof TY[g[1]]&&(TY[g[1]]={}),d+=isNaN(f,10)?"?_v="+b:"?_t="+parseInt(f?h/f:h,10),a[i].path=d,TY.module.add(i,a[i])}};return z.init=TY.module&&TY.module.init||function(){},z}();TY.module.init();
TY.extend(TY,{TY_interface:function(){var a;return a={path:"http://static.tianyaui.com/global/ty2.0/core/core_interface.js?_v="+(new Date).TY_format("yyyydh"),rely:null,type:"js",charset:"utf-8"},TY.module.add("TY.core.interface",a),"TY.core.interface"}(),_getPara:function(a){var d={args:null,cbk:function(){},seq:!0},b=a.length-1;return 0<=b&&"number"===TY.type(a[b])&&(d.waitTime=a[b--]),0<=b&&"boolean"===TY.type(a[b])&&(d.seq=a[b--]),0<=b&&"function"===TY.type(a[b])&&(d.cbk=a[b--]),0>b?!1:(d.args=
Array.prototype.slice.call(a,0,b+1),"array"==typeof d.args[0]&&(d.args=d.args[0]),d)},_loaderBack:function(a,d){for(var b=[],c=0,f=a.length;f>c;c++){for(var g=a[c].split("."),h=window,j=0,s=g.length;s>j;j++)h=h&&"undefined"!=typeof h[g[j]]?h[g[j]]:null;b.push(h)}d.apply(this,b)},_isInterfaceRegiser:function(a){for(var d=TY.module.getInterface()||{},b=0,c=0,f=a.length;f>c;c++)"undefined"!=typeof d[a[c]]&&b++;return f==b?!0:!1},loader:function(){function a(){d._loaderBack(b.args,b.cbk)}var d=this,b=
d._getPara(arguments),c=d.TY_interface;if(!1!==b){var f=b.args;d._isInterfaceRegiser(f)?TY.module.loadInterface(f,a,b.seq):TY.module.isLoadedInterface(c)?b.cbk(!1):TY.module.loadInterface(c,function(c){c&&d._isInterfaceRegiser(f)?TY.module.loadInterface(f,a,b.seq):b.cbk(!1)})}},loadUrl:function(){var a=this._getPara(arguments);!1!==a&&TY.module.loadUrl(a.args,a.cbk,a.seq,a.waitTime)},isLoadedModule:function(a){return TY.module.isLoadedInterface(a)},loadedModule:function(a){TY.module.loadedInterface(a)}});
(function(){var a,d,b=["loadUrl","loader"];if((d=TY._args)&&(a=d.length))for(var c=0;a>c;c+=2)TY[b[d[c]]].apply(TY,d[c+1])})();"undefined"==typeof define&&TY.namespace("widget");var _hmt=_hmt||[];
$(function(){(function(){var a=[];a.push('<center><span style="font-size:12px;">WAP版权归属:<a href="http://www.zhengyingkeji.com">北京正影网络科技有限公司</a></span></center>');var d;if(d=!/^http:\/\/passport.tianya.cn\/register|login_m.jsp/.test(window.location.href))d=TY.param.getHrefParam(),
d=!(d&&(/^[iac]$/i.test(d.f)||/^daily/i.test(d.f)));d&&$("body").append(a.join(""))})();$(".list-set .item-user").size()&&__global.isOnline()&&$.loadUrl("http://www.tianya.cn/api/tw?method=messagecount.ice.select&params.userId="+__global.getUserId()+"&var=USERMSG&_="+(new Date).getTime(),function(a){a&&window.USERMSG&&1==USERMSG.success&&1==USERMSG.code&&(a=USERMSG.data,0<a.userCount+a.atMeCount&&$(".list-set .item-user").find("a").append('<i class="icon-msg"></i>'))});$.loadUrl("http://static.tianyaui.com/global/ty/stat/stat_20080313.js");
$.loadUrl("http://hm.baidu.com/h.js?bc5755e0609123f78d0e816bf7dee255",function(a){if(a&&(a=TY.param.getHrefParam())&&a.event)a=a.event.split("|"),2==a.length&&_hmt.push(["_trackEvent",a[1],a[0],"",""])})});
