<?php
Define('W_NUMBER','2040');
Define('W_COMPANY','xxx有限公司');
Define('W_NAME','xxx');
Define('W_CONTACT','xxx');
Define('W_PROVINCE','2');
Define('W_CITY','52');
Define('W_ADRESS','xxx');
Define('W_MOBILE','010-111111');
Define('W_MAIL','seo@1111111.cn');
Define('W_LOGO','static/upload/images/web3_so_com/logo/logo.png');
Define('W_EDIT','KindEdit');
Define('W_EXPIRYDATE','1487952000');
Define('W_DOMAIN','');
Define('W_STATUS','0');
Define('W_TIME','');
Define('W_ONLINESELL','10');
Define('W_ONLINEBUY','10');
Define('W_NEXTLINESELL','1');
Define('W_NEXLINEBUY','2');
?>